# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7a42614c50798ada2164df2ff4fbd32b34a003e8c43f50e6519ddd6d585254de9c47a09f195c6e199350b873209464a3cf6588804723b5cd1f084bedfcef902

test:
  secret_key_base: f58c20f3dad11aa292200acb30d5de0a44ad565210d5897b3934ef40e6e7e5098361ce3e39917440c416b6b61ae5c491202ca61edbde6a031a453ce48fe6481a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
